Repository keycloak/keycloak-documentation, pull requests merged in 2020-10, with the labels that each got.

#1045 KEYCLOAK-15770 Skip creating session for docker protocol authentication
  server_admin/topics.adoc
  server_admin/topics/sessions/transient.adoc
  server_admin/topics/sso-protocols/docker.adoc
  upgrading/topics/keycloak/changes.adoc
Labels: kind/enhancement, status/merge-with-code

#1052 FAPI RW support to release notes
  release_notes/topics/12_0_0.adoc
Labels: status/in-review

#807 KEYCLOAK-10376 Improve load balance and proxy documentation
  server_installation/keycloak-images/load_balancer.png
  server_installation/keycloak-images/load_balancer.svg
  server_installation/rhsso-images/load_balancer.png
  server_installation/rhsso-images/load_balancer.svg
  server_installation/topics/clustering/load-balancer.adoc
Labels: kind/enhancement
