Repository keycloak/keycloak-documentation, pull requests merged in 2020-07, with the labels that each got.

#897 KEYCLOAK-13562 removing duplicate text
  openshift/topics/reference.adoc
Labels: kind/bug, status/in-review

#875 KEYCLOAK-13289 Added redirect_url to Node.js logout
  securing_apps/topics/oidc/nodejs-adapter.adoc
Labels: status/merge-with-code

#945 KEYCLOAK 12209 Adding note about Z Series
  release_notes/topics/product/7_4_final.adoc
Labels: status/ready

#956 Update auth-services-architecture.adoc
  authorization_services/topics/auth-services-architecture.adoc
Labels: area/authorization

#958 KEYCLOAK-14467 Improve the brute force docs about the error message f…
  server_admin/topics/threat/brute-force.adoc
Labels: status/ready

#859 Updated section on the `Credentials` tab
  server_admin/topics/clients/oidc/confidential.adoc
Labels: area/authentication

#947 KEYCLOAK-13267 Add note to upgrade guide about keycloak-admin-client version
  upgrading/topics/keycloak/upgrading.adoc
  upgrading/topics/upgrade_admin_client.adoc
Labels: kind/enhancement

#971 KEYCLOAK-14023 Instagram User Endpoint change
  server_admin/images/instagram-add-new-app.png
  server_admin/images/instagram-add-platform.png
  server_admin/images/instagram-add-product.png
  server_admin/images/instagram-app-settings.png
  server_admin/images/instagram-create-app-id.png
  server_admin/images/instagram-create-instagram-app-id.png
  server_admin/keycloak-images/instagram-add-identity-provider.png
  server_admin/rhsso-images/instagram-add-identity-provider.png
  server_admin/topics.adoc
  server_admin/topics/identity-broker/social/instagram.adoc
  upgrading/topics/keycloak/changes.adoc
Labels: status/merge-with-code

#950 KEYCLOAK-14361 make tests run as final module regardless of profile (community|product)
  pom.xml
Labels: kind/bug

#976 KEYCLOAK-14715 Documentation for the upgrade to Wildfly 20
  server_installation/topics/operating-mode/crossdc.adoc
  topics/templates/document-attributes-community.adoc
  upgrading/topics/keycloak/changes.adoc
Labels: area/server, priority/critical, status/merge-with-code

#923 KEYCLOAK-13950 SAML2 Identity Provider - Send Subject in SAML requests
  server_admin/topics/identity-broker/saml.adoc
Labels: area/saml, status/merge-with-code

#963 KEYCLOAK-14529 Signed and Encrypted ID Token Support : RSA-OAEP-256
  server_admin/topics/clients/client-oidc.adoc
Labels: status/merge-with-code

#881 KEYCLOAK-13280 correcting OpenShift cluster setup
  openshift/topics/get_started.adoc
Labels: status/in-review
