Repository keycloak/keycloak-documentation, pull requests merged in 2021-01, with the labels that each got.

#1071 KEYCLOAK-14846 default roles processing
  release_notes/topics/13_0_0.adoc
  server_admin/topics/roles/user-role-mappings/default-roles.adoc
Labels: area/storage, kind/enhancement, status/merge-with-code

#1072 KEYCLOAK-11908 Support for conditional creating indices based on number
  upgrading/topics/migrate_db.adoc
Labels: status/merge-with-code

#1086 KEYCLOAK-14019 Improvements for request_uri configuration
  upgrading/topics/keycloak/changes.adoc
Labels: status/merge-with-code

#1084 [KEYCLOAK-16373] Document the streamified variant of the user storage…
  server_development/topics.adoc
  server_development/topics/user-storage/provider-capability-interfaces.adoc
  server_development/topics/user-storage/stream-interfaces.adoc
Labels: area/storage, kind/enhancement
