Repository keycloak/keycloak-documentation, pull requests merged in 2021-11, with the labels that each got.

#1248 KEYCLOAK-18497 - UserProfile - support different input types in built-in dynamic forms
  server_admin/images/user-profile-select-options-custom-validator.png
  server_admin/images/user-profile-select-options-simple-i18n.png
  server_admin/images/user-profile-select-options-simple.png
  server_admin/topics/users/user-profile.adoc
Labels: kind/feature

#1201 KEYCLOAK-15291 Revise Server Installation guide to meet Red Hat standards
  securing_apps/topics/saml/java/logout.adoc
  server_installation/topics/cache.adoc
  server_installation/topics/cache/clear.adoc
  server_installation/topics/cache/disable.adoc
  server_installation/topics/cache/eviction.adoc
  server_installation/topics/cache/replication.adoc
  server_installation/topics/clustering.adoc
  server_installation/topics/clustering/booting.adoc
  server_installation/topics/clustering/example.adoc
  server_installation/topics/clustering/load-balancer.adoc
  server_installation/topics/clustering/multicast.adoc
  server_installation/topics/clustering/recommended.adoc
  server_installation/topics/clustering/securing-cluster-comm.adoc
  server_installation/topics/clustering/serialized.adoc
  server_installation/topics/config-subsystem.adoc
  server_installation/topics/config-subsystem/cli-recipes.adoc
  server_installation/topics/config-subsystem/configure-spi-providers.adoc
  server_installation/topics/config-subsystem/start-cli.adoc
  server_installation/topics/database.adoc
  server_installation/topics/database/checklist.adoc
  server_installation/topics/database/datasource.adoc
  server_installation/topics/database/jdbc.adoc
  server_installation/topics/database/unicode-considerations.adoc
  server_installation/topics/host.adoc
  server_installation/topics/installation.adoc
  server_installation/topics/installation/directory-structure.adoc
  server_installation/topics/installation/distribution-files-community.adoc
  server_installation/topics/installation/distribution-files-product.adoc
  server_installation/topics/installation/installing-rpm.adoc
  server_installation/topics/installation/system-requirements.adoc
  server_installation/topics/network.adoc
  server_installation/topics/network/bind-address.adoc
  server_installation/topics/network/https.adoc
  server_installation/topics/network/outgoing.adoc
  server_installation/topics/network/ports.adoc
  server_installation/topics/operating-mode.adoc
  server_installation/topics/operating-mode/crossdc.adoc
  server_installation/topics/operating-mode/crossdc/assembly-setting-up-crossdc.adoc
  server_installation/topics/operating-mode/crossdc/proc-configuring-infinispan.adoc
  server_installation/topics/operating-mode/crossdc/proc-setting-up-infinispan.adoc
  server_installation/topics/operating-mode/domain.adoc
  server_installation/topics/operating-mode/standalone-ha.adoc
  server_installation/topics/operating-mode/standalone.adoc
  server_installation/topics/operator/keycloak-cr.adoc
  server_installation/topics/overview/recommended-reading.adoc
Labels: status/needs-rebase

#1058 KEYCLOAK-15109 Ingress/Route Host Override
  server_installation/topics/operator/keycloak-cr.adoc
Labels: status/needs-rebase

#1270 KEYCLOAK-18276 client content screen enhancement
  server_admin/topics/clients/oidc/con-basic-settings.adoc
  server_admin/topics/clients/saml/proc-creating-saml-client.adoc
Labels: kind/enhancement
