Repository keycloak/keycloak-documentation, pull requests merged in 2021-02, with the labels that each got.

#1103 KEYCLOAK-4544 Detect existing user before granting user autolink
  server_admin/topics/identity-broker/first-login-flow.adoc
Labels: status/merge-with-code

#948 Update resource-overview.adoc
  authorization_services/topics/resource-overview.adoc
Labels: area/authorization

#1000 KEYCLOAK-14157 Correcting template name and table problem.
  openshift/topics/advanced_concepts.adoc
  openshift/topics/get_started.adoc
Labels: status/hold
